title: Cato's Coding Blog
subtitle: Cato

collections:
  computer science:
    output: true
  issue:
    output: true
  resources:
    output: true

defaults:
  - 
    scope:
      path: ""
    values:
      layout: "default"

author:
  name: cato
  email: mpcato@naver.com
  github: porciuscato
  bio: Hope you have a good day:)
  linkedin: jinhong-park-8119a2160
  instagram: __jin__hong__

paginate: 5

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

markdown: CommonMarkGhPages

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]